### ISSUE TITLE
[BUG]: Test bug report template delete me

### ISSUE THREAD

**Issue by tonnrueter** [tonnrueter/remind#5]
### Your environment

**REMIND version**
123

**R version**
123

**Operating System**
Wion 11

### Expected Behavior

Feasible!

### Actual Behavior

Infeasible!

### Steps to Reproduce the Problem

1. Ran `R start.R`

### Relevant Log Output

[dummy.log](https://github.com/tonnrueter/remind/files/13940299/dummy.log)

### Please confirm the following

- [X] I have access to the PIK cluster
- [ ] I have access to the REMIND input data
- [X] I have searched the existing issues
- [X] I have provided detailed information about the bug
- [X] I have provided steps to reproduce the issue
- [X] I have provided information about my environment (OS)

**Comment by LaviniaBaumstark** [comment]
could it be missleading asking them to confirm if they have access to PIK cluster and REMIND inptu data? Sounds like as if they should have. But this bug report is more for external users. So, maybe split out those two questions and call ist something like `further information regarding environment`?

**Comment by tonnrueter** [comment]
Michaja similarly suggested this [here](https://github.com/remindmodel/remind/pull/1521/files/f6a13c676716fc3b82f7af0137a9a446528b9677#discussion_r1453406769). I changed it already, however the new bug report issue template 

1. Was already moved to my `develop` branch (this was necessary for the issue templates to show up when clicking on "New Issue" in my repo) and I realize this at first and
2. Had an error due to the now empty title string (which GH does not like)

Both issues are now fixed 👍 [Here is a new bug report](https://github.com/tonnrueter/remind/issues/7) reflecting your suggestion. If you wanna test the form itself either [checkout the file itself](https://github.com/tonnrueter/remind/blob/develop/.github/ISSUE_TEMPLATE/bug.yml) or [submit a new test issue](https://github.com/tonnrueter/remind/issues/new/choose)

**Comment by LaviniaBaumstark** [comment]
like the new template
